
# Errors


When doing a long-running computation with `future.batchtools`, you may get the following errors under `plan(remote)`

```
client_loop: send disconnect: Broken pipe
Connection to <host address> closed by remote host.
```
